language: python

python:
  - "3.6"

install:
  # We do this conditionally because it saves us some downloading if the version is the same.
  - sudo apt-get update
  - sudo apt-get install gfortran python3-setuptools python3-sphinx
  # Get petsc
  #- git clone -b maint https://gitlab.com/petsc/petsc.git petsc
  # Set petsc enviroment
  #- cd petsc
  #- export PETSC_DIR=$PWD
  #- export PETSC_ARCH=arch-linux2-c-debug
  # Then, build and install PETSc:
  #- ./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran  --download-mpich --download-fblaslapack --with-scalar-type=complex --download-mumps --download-scalapack --download-parmetis --download-metis --download-ptscotch --download-cmake
  #- make $PETSC_DIR $PETSC_ARCH all
  # Uncomment next two lines to activate petsc tests
  #- make $PETSC_DIR $PETSC_ARCH test
  #- make $PETSC_DIR $PETSC_ARCH streams
  # Ensure mpicc compiler wrapper is on your search path:
  #- export PATH="${PETSC_DIR}/${PETSC_ARCH}/bin:${PATH}"
  #- cd ..
  # Install petgem requirements
  - pip install numpy scipy singleton_decorator pytest
  # Install petgem by git repo
  #- python3 setup.py build
  #- sudo python3 setup.py install --install-dir=$PWD
  #- sudo easy_install . --install-dir $PWD
  #easy_install . --install-dir /usr/lib/python2.7/dist-packages
  #- pip install petgem

script:
  - ls
  - python -c 'import numpy; print(numpy.version.version)'
  #- cd doc; make html; cd ..
  #- mpirun -n 2 py.test test/test_mpi.py
  #- mpirun -n 2 py.test test/test_petsc.py

#after_success:
#  - sbt coveralls





# language: python
#
# install:

#   # Install and create virtual env
#   - sudo apt-get install python3-virtualenv
#   - virtualenv -p python ~/petgem
#   - source ~/petgem/bin/activate
#   # Install compilers and libraries
#   - sudo apt-get install gfortran
#   # Get petsc
#   - git clone -b maint https://gitlab.com/petsc/petsc.git petsc
#   # Set petsc enviroment
#   - cd petsc
#   - export PETSC_DIR=$PWD
#   - export PETSC_ARCH=arch-linux2-c-debug
#   # Then, build and install PETSc:
#   - ./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran  --download-mpich --download-fblaslapack --with-scalar-type=complex --download-mumps --download-scalapack --download-parmetis --download-metis --download-ptscotch --download-cmake
#   - make $PETSC_DIR $PETSC_ARCH all
#   # Uncomment next two lines to activate petsc tests
#   #- make $PETSC_DIR $PETSC_ARCH test
#   #- make $PETSC_DIR $PETSC_ARCH streams
#   # Ensure mpicc compiler wrapper is on your search path:
#   - export PATH="${PETSC_DIR}/${PETSC_ARCH}/bin:${PATH}"
#   # Ensure Numpy is installed:
#   - pip3 install -U numpy
#   # Ensure setuptools is installed:
#   - sudo apt-get install -U python3-setuptools
#   # Ensure pytest is installed:
#   - pip3 install -U pytest
#   # Install petgem by git repo
#   - git clone https://github.com/ocastilloreyes/petgem.git --branch 0.7
#   - cd petgem
#   - python3 setup.py build
#   - sudo python3 setup.py install
#
# script:
#   - cd doc; make html; cd ..
#   - mpirun -n 2 py.test test/test_mpi.py
#   - mpirun -n 2 py.test test/test_petsc.py
#   - mpirun -n 2 py.test test/test_petgem.py
#
# after_success:
#   - sbt coveralls
